declare module "@design-system/icons";

export { default as Alert } from "./Alert";
export { default as Apps } from "./Apps";
export { default as Book } from "./Book";
export { default as Camera } from "./Camera";
export { default as Chat } from "./Chat";
export { default as Check } from "./Check";
export { default as Close } from "./Close";
export { default as Cloud } from "./Cloud";
export { default as CreditCard } from "./CreditCard";
export { default as Edit } from "./Edit";
export { default as Email } from "./Email";
export { default as Equalizer } from "./Equalizer";
export { default as Home } from "./Home";
export { default as Info } from "./Info";
export { default as Link } from "./Link";
export { default as Menu } from "./Menu";
export { default as Photo } from "./Photo";
export { default as Remove } from "./Remove";
export { default as Search } from "./Search";
export { default as Settings } from "./Settings";
export { default as ShoppingCart } from "./ShoppingCart";
export { default as Success } from "./Success";
export { default as Time } from "./Time";
export { default as User } from "./User";
